version: '3'

services:
  db:
    container_name: sarayut-postgres
    ports:
      - 54322:5432
    environment:
      - POSTGRES_USER=sarayut
      - POSTGRES_PASSWORD=123456789
    image: postgres:14.4
    restart: unless-stopped

  pgadmin:
    container_name: sarayut-pgadmin
    ports:
      - 4433:443
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=sarayut-so@rmutp.ac.th
      - PGADMIN_DEFAULT_PASSWORD=123456789
    image: dpage/pgadmin4:latest
    restart: unless-stopped

  strapi:
    container_name: sarayut-myapp
    ports:
      - 1337:1337
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=172.22.128.1
      - DATABASE_PORT=54322
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=sarayut
      - DATABASE_PASSWORD=123456789
      - DATABASE_SSL=false
    image: naskio/strapi:latest
    restart: unless-stopped